name: Flask API Testleri

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodlari GitHub'dan çek
      uses: actions/checkout@v4

    - name: Python 3.12 Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Bağimlilikleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pytest ile Testleri Çalistir
      run: |
        python -m pytest